environment:
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"

branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+/

install:
  - "%PYTHON%\\Scripts\\pip.exe install poetry"
  - "%PYTHON%\\Scripts\\poetry.exe install"

build: off

cache:
  - '%LOCALAPPDATA%\pip\Cache'

test_script:
  - "%PYTHON%\\Scripts\\poetry.exe run pytest --cov=latex2mathml --cov-report=xml -v"
  - "%PYTHON%\\Scripts\\poetry.exe run pycodestyle --verbose"

on_success:
  - "%PYTHON%\\Scripts\\poetry.exe run codecov -f coverage.xml"
